export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL';

export const TASK_SELECT_SUCCESS = 'TASK_SELECT_SUCCESS';
export const TASK_SELECT_REQUEST = 'TASK_SELECT_REQUEST';
export const TASK_SELECT_FAIL = 'TASK_SELECT_FAIL';

export const TASK_CREATE_SUCCESS = 'TASK_CREATE_SUCCESS';
export const TASK_CREATE_REQUEST = 'TASK_CREATE_REQUEST';
export const TASK_CREATE_FAIL = 'TASK_CREATE_FAIL';

export const TASK_DELETE_SUCCESS = 'TASK_DELETE_SUCCESS';
export const TASK_DELETE_REQUEST = 'TASK_DELETE_REQUEST';
export const TASK_DELETE_FAIL = 'TASK_DELETE_FAIL';
