export const TASK_LIST_REQUEST = 'TASK_LIST_REQUEST';
export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS';
export const TASK_LIST_FAIL = 'TASK_LIST_FAIL';

export const TASK_SELECT_SUCCESS = 'TASK_SELECT_SUCCESS';
export const TASK_SELECT_REQUEST = 'TASK_SELECT_REQUEST';
export const TASK_SELECT_FAIL = 'TASK_SELECT_FAIL';
